In [305]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
aids=pd.read_csv('aid-effectiveness.csv')
gender=pd.read_csv('gender.csv')
social_dev=pd.read_csv('social-development.csv')
trade=pd.read_csv('trade.csv')

In [4]:
def remove_avg(col):
    if 'average_value_' in col:
        return col.replace('average_value_', '')
    return col

In [ ]:
aids.columns=[remove_avg(col) for col in aids.columns]

In [6]:
aids['Primary completion rate, total (% of relevant age group)'].max()

np.float64(134.542510986328)

In [7]:
aids

,Country Name,Country Code,Year,"Grants, excluding technical cooperation (BoP, current US$)","Incidence of tuberculosis (per 100,000 people)","Maternal mortality ratio (modeled estimate, per 100,000 live births)","Mortality rate, under-5 (per 1,000 live births)",Net ODA received (% of GNI),Net ODA received (% of gross capital formation),"Net ODA received (% of imports of goods, services and primary income)",Net ODA received per capita (current US$),"Net bilateral aid flows from DAC donors, Belgium (current US$)","Net bilateral aid flows from DAC donors, European Union institutions (current US$)","Net bilateral aid flows from DAC donors, Japan (current US$)","Net bilateral aid flows from DAC donors, Luxembourg (current US$)","Net bilateral aid flows from DAC donors, Netherlands (current US$)","Net bilateral aid flows from DAC donors, New Zealand (current US$)","Net bilateral aid flows from DAC donors, Norway (current US$)","Net bilateral aid flows from DAC donors, Poland (current US$)","Net bilateral aid flows from DAC donors, Portugal (current US$)","Net bilateral aid flows from DAC donors, Slovak Republic (current US$)","Net bilateral aid flows from DAC donors, Slovenia (current US$)","Net bilateral aid flows from DAC donors, Sweden (current US$)","Net bilateral aid flows from DAC donors, Switzerland (current US$)","Net bilateral aid flows from DAC donors, Total (current US$)","Net bilateral aid flows from DAC donors, United Kingdom (current US$)","Net bilateral aid flows from DAC donors, United States (current US$)",Net migration,Net official aid received (constant 2018 US$),Net official aid received (current US$),Net official development assistance and official aid received (constant 2018 US$),Net official development assistance and official aid received (current US$),Net official development assistance received (constant 2018 US$),Net official development assistance received (current US$),"Net official flows from UN agencies, FAO (current US$)","Net official flows from UN agencies, IAEA (current US$)","Net official flows from UN agencies, IFAD (current US$)","Net official flows from UN agencies, ILO (current US$)","Net official flows from UN agencies, UNAIDS (current US$)","Net official flows from UN agencies, UNDP (current US$)","Net official flows from UN agencies, UNFPA (current US$)","Net official flows from UN agencies, UNHCR (current US$)","Net official flows from UN agencies, UNICEF (current US$)","Net official flows from UN agencies, UNPBF (current US$)","Net official flows from UN agencies, UNTA (current US$)","Net official flows from UN agencies, WFP (current US$)","Net official flows from UN agencies, WHO (current US$)",Pregnant women receiving prenatal care (%),"Prevalence of HIV, total (% of population ages 15-49)","Primary completion rate, total (% of relevant age group)","School enrollment, primary and secondary (gross), gender parity index (GPI)","Technical cooperation grants (BoP, current US$)","Vulnerable employment, total (% of total employment) (modeled ILO estimate)"
0,Africa Eastern and Southern,AFE,1987,NaN,NaN,NaN,183.560534,4.507926,23.356231,17.865711,27.081263,2.039800e+08,4.540100e+08,4.125000e+08,NaN,3.597500e+08,4.800000e+05,2.409700e+08,NaN,NaN,NaN,NaN,3.078200e+08,8.847000e+07,5.356970e+09,2.970000e+08,4.970000e+08,-147864.0,NaN,NaN,1.373310e+10,7.560670e+09,1.373310e+10,7.560670e+09,NaN,NaN,7.413000e+07,NaN,NaN,1.258200e+08,1.170000e+07,1.544200e+08,8.690000e+07,NaN,3.153000e+07,1.974300e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Albania,ALB,1977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-99.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Albania,ALB,2019,149840000.0,16.0,NaN,9.700000,0.188334,NaN,0.373940,9.953784,3.000000e+04,7.198000e+07,-1.130000e+06,1.900000e+05,1.100000e+05,NaN,1.360000e+06,289999.991655,NaN,509999.990463,319999.992847,1.351000e+07,3.061000e+07,2.133600e+08,3.520000e+06,1.704000e+07,NaN,NaN,NaN,3.141000e+07,2.841000e+07,3.141000e+07,2.841000e+07,359183.281660,157039.016485,-1.542000e+06,442380.011082,NaN,5.380900e+05,7.833047e+05,6.849278e+04,2.605000e+06,NaN,NaN,NaN,382119.864225,NaN,0.1,103.322746,1.01863,102990000.0,51.200001
3,Armenia,ARM,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2,NaN,NaN,NaN,NaN
4,Azerbaijan,AZE,2013,106280000.0,78.0,28.0,30.400000,-0.101133,-0.372220,-0.287345,-7.521663,NaN,1.738000e+07,4.285000e+07,1.000000e+04,6.000000e+04,NaN,1.970000e+06,300000.011921,NaN,39999.999106,NaN,8.700000e+05,5.680000e+06,1.181800e+08,4.140000e+06,3.313000e+07,NaN,NaN,NaN,-7.301000e+07,-7.083000e+07,-7.301000e+07,-7.083000e+07,692265.808582,200000.002980,7.800000e+06,148134.917021,100831.791759,1.102744e+06,7.267360e+05,NaN,1.063733e+06,NaN,NaN,NaN,223254.367709,NaN,0.1,88.089409,NaN,39920000.0,56.430000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14596,Latin America & the Caribbean (IDA & IBRD coun...,TLA,1971,NaN,NaN,NaN,NaN,0.325422,1.452849,NaN,2.076328,3.450000e+06,9.730000e+06,-1.119000e+07,NaN,3.009000e+07,NaN,5.000000e+04,NaN,NaN,NaN,NaN,1.000000e+06,1.870000e+06,5.092300e+08,1.484000e+07,3.590000e+08,NaN,NaN,NaN,3.126700e+09,5.825200e+08,3.126700e+09,5.825200e+08,NaN,NaN,NaN,NaN,NaN,3.960000e+07,NaN,2.000000e+04,4.760000e+06,NaN,4.530000e+06,1.541000e+07,NaN,NaN,NaN,80.362923,0.96536,NaN,NaN
14597,Tonga,TON,1997,8050000.0,NaN,NaN,18.800000,11.665676,67.502300,NaN,265.677235,NaN,2.100000e+06,7.950000e+06,NaN,NaN,5.560000e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.454000e+07,NaN,1.000000e+06,-8435.0,NaN,NaN,3.668000e+07,2.567000e+07,3.668000e+07,2.567000e+07,NaN,NaN,1.500000e+05,NaN,NaN,4.000000e+04,5.000000e+04,NaN,NaN,NaN,8.500000e+05,NaN,NaN,NaN,NaN,NaN,NaN,16880000.0,58.160000
14598,St. Vincent and the Grenadines,VCT,1999,13530000.0,NaN,NaN,22.300000,4.441640,NaN,6.279778,153.020979,NaN,7.250000e+06,5.170000e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.320000e+07,6.300000e+05,-2.500000e+05,NaN,NaN,NaN,2.090000e+07,1.649000e+07,2.090000e+07,1.649000e+07,NaN,NaN,1.000000e+05,NaN,NaN,7.000000e+04,1.000000e+04,NaN,NaN,NaN,1.700000e+05,NaN,NaN,91.8,NaN,NaN,NaN,1990000.0,20.009999
14599,Vietnam,VNM,1996,231150000.0,NaN,NaN,36.700000,3.751074,13.136658,7.079639,11.966808,1.476000e+07,1.987000e+07,1.208500e+08,2.590000e+06,2.966000e+07,2.310000e+06,4.180000e+06,NaN,NaN,NaN,NaN,4.624000e+07,1.014000e+07,4.966300e+08,8.390000e+06,NaN,NaN,NaN,NaN,1.119140e+09,9.103000e+08,1.119140e+09,9.103000e+08,NaN,NaN,2.590000e+06,NaN,NaN,9.770000e+06,4.500000e+06,NaN,1.210000e+07,NaN,1.760000e+06,9.860000e+06,NaN,NaN,0.1,NaN,NaN,234360000.0,82.380001
14600,"Yemen, Rep.",YEM,1970,9650000.0,NaN,NaN,326.700000,NaN,NaN,NaN,2.722262,NaN,1.200000e+06,1.000000e+04,NaN,2.400000e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+05,1.039000e+07,1.210000e+06,3.000000e+06,NaN,NaN,NaN,1.088800e+08,1.686000e+07,1.088800e+08,1.686000e+07,NaN,NaN,NaN,NaN,NaN,1.480000e+06,NaN,NaN,3.700000e+05,NaN,6.100000e+05,3.650000e+06,NaN,NaN,NaN,NaN,NaN,4860000.0,NaN

In [36]:
aids[aids['Country Name']=='South Africa']

,Country Name,Country Code,Year,"Grants, excluding technical cooperation (BoP, current US$)","Incidence of tuberculosis (per 100,000 people)","Maternal mortality ratio (modeled estimate, per 100,000 live births)","Mortality rate, under-5 (per 1,000 live births)",Net ODA received (% of GNI),Net ODA received (% of gross capital formation),"Net ODA received (% of imports of goods, services and primary income)",Net ODA received per capita (current US$),"Net bilateral aid flows from DAC donors, Belgium (current US$)","Net bilateral aid flows from DAC donors, European Union institutions (current US$)","Net bilateral aid flows from DAC donors, Japan (current US$)","Net bilateral aid flows from DAC donors, Luxembourg (current US$)","Net bilateral aid flows from DAC donors, Netherlands (current US$)","Net bilateral aid flows from DAC donors, New Zealand (current US$)","Net bilateral aid flows from DAC donors, Norway (current US$)","Net bilateral aid flows from DAC donors, Poland (current US$)","Net bilateral aid flows from DAC donors, Portugal (current US$)","Net bilateral aid flows from DAC donors, Slovak Republic (current US$)","Net bilateral aid flows from DAC donors, Slovenia (current US$)","Net bilateral aid flows from DAC donors, Sweden (current US$)","Net bilateral aid flows from DAC donors, Switzerland (current US$)","Net bilateral aid flows from DAC donors, Total (current US$)","Net bilateral aid flows from DAC donors, United Kingdom (current US$)","Net bilateral aid flows from DAC donors, United States (current US$)",Net migration,Net official aid received (constant 2018 US$),Net official aid received (current US$),Net official development assistance and official aid received (constant 2018 US$),Net official development assistance and official aid received (current US$),Net official development assistance received (constant 2018 US$),Net official development assistance received (current US$),"Net official flows from UN agencies, FAO (current US$)","Net official flows from UN agencies, IAEA (current US$)","Net official flows from UN agencies, IFAD (current US$)","Net official flows from UN agencies, ILO (current US$)","Net official flows from UN agencies, UNAIDS (current US$)","Net official flows from UN agencies, UNDP (current US$)","Net official flows from UN agencies, UNFPA (current US$)","Net official flows from UN agencies, UNHCR (current US$)","Net official flows from UN agencies, UNICEF (current US$)","Net official flows from UN agencies, UNPBF (current US$)","Net official flows from UN agencies, UNTA (current US$)","Net official flows from UN agencies, WFP (current US$)","Net official flows from UN agencies, WHO (current US$)",Pregnant women receiving prenatal care (%),"Prevalence of HIV, total (% of population ages 15-49)","Primary completion rate, total (% of relevant age group)","School enrollment, primary and secondary (gross), gender parity index (GPI)","Technical cooperation grants (BoP, current US$)","Vulnerable employment, total (% of total employment) (modeled ILO estimate)"
213,South Africa,ZAF,2018,824260000.0,677.0,NaN,35.0,0.258277,1.394135,0.719447,15.938741,1.150000e+07,1.760000e+07,9.140000e+06,5.800000e+05,4.400000e+05,5.000000e+04,4.640000e+06,29999.999329,1.380000e+06,NaN,NaN,3.840000e+06,1.575000e+07,7.894300e+08,3.929000e+07,5.756500e+08,NaN,NaN,NaN,9.211400e+08,9.211400e+08,9.211400e+08,9.211400e+08,251219.987869,319094.985723,NaN,1.003371e+06,3.002010e+05,1.497066e+05,1.039680e+06,NaN,1.289124e+06,NaN,NaN,NaN,1.823966e+06,NaN,19.4,90.344498,1.00301,116370000.0,10.320000
509,South Africa,ZAF,1999,247650000.0,NaN,NaN,69.3,0.407177,2.334096,1.539716,12.252769,4.480000e+06,1.367300e+08,1.406000e+07,1.140000e+06,2.658000e+07,8.000000e+05,1.586000e+07,NaN,1.200000e+05,NaN,NaN,4.088000e+07,5.720000e+06,5.229600e+08,6.292000e+07,8.460000e+07,NaN,NaN,NaN,7.792400e+08,5.432700e+08,7.792400e+08,5.432700e+08,NaN,NaN,NaN,NaN,NaN,3.000000e+06,8.800000e+05,3.870000e+06,5.180000e+06,NaN,2.800000e+06,NaN,NaN,NaN,10.9,79.950081,1.03142,212860000.0,10.600000
797,South Africa,ZAF,2014,736850000.0,1070.0,128.0,38.1,0.315453,1.497769,0.812811,19.752794,1.890000e+07,1.988900e+08,7.400000e+06,3.100000e+05,3.100000e+06,2.800000e+05,9.630000e+06,50000.000745,1.620000e+06,NaN,NaN,7.110000e+06,1.102000e+07,9.330700e+08,-3.026000e+07,5.150200e+08,NaN,NaN,NaN,1.074930e+09,1.077400e+09,1.074930e+09,1.077400e+09,NaN,959999.978542,NaN,7.182300e+05,2.015598e+06,8.554240e+05,1.949127e+06,NaN,1.353978e+06,NaN,NaN,510519.981384,1.621257e+06,NaN,19.0,NaN,1.01611,165190000.0,8.830000
1358,South Africa,ZAF,1967,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,199359.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1428,South Africa,ZAF,1972,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,222659.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1511,South Africa,ZAF,2001,212530000.0,867.0,168.0,73.0,0.364145,2.241692,1.149575,9.411192,6.120000e+06,9.921000e+07,1.339000e+07,3.900000e+05,3.484000e+07,8.000000e+05,1.699000e+07,NaN,1.100000e+05,NaN,NaN,2.645000e+07,8.040000e+06,4.129800e+08,4.176000e+07,8.585000e+07,NaN,NaN,NaN,6.755200e+08,4.288800e+08,6.755200e+08,4.288800e+08,NaN,NaN,NaN,NaN,NaN,1.540000e+06,1.580000e+06,3.820000e+06,1.950000e+06,NaN,2.630000e+06,NaN,NaN,NaN,13.2,NaN,1.01854,220700000.0,10.850000
1575,South Africa,ZAF,1975,NaN,NaN,NaN,121.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2185,South Africa,ZAF,1978,NaN,NaN,NaN,102.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2532,South Africa,ZAF,2019,608300000.0,615.0,NaN,34.5,0.284455,1.571634,0.801935,16.589971,1.047000e+07,1.443600e+08,1.003000e+07,1.300000e+05,7.500000e+05,8.000000e+04,4.250000e+06,170000.001788,1.230000e+06,NaN,NaN,4.920000e+06,1.078000e+07,8.633000e+08,4.279000e+07,3.904800e+08,NaN,NaN,NaN,9.827700e+08,9.714800e+08,9.827700e+08,9.714800e+08,498934.596777,445241.630077,NaN,1.456450e+06,2.229377e+06,1.747919e+06,1.969309e+06,NaN,7.742000e+06,NaN,NaN,NaN,1.812950e+06,NaN,19.3,NaN,NaN,124790000.0,10.670000
2621,South Africa,ZAF,2007,565740000.0,1270.0,199.0,75.3,0.274513,1.265431,0.696053,16.187373,1.475000e+07,1.446500e+08,4.670000e+06,3.800000e+05,4.487000e+07,1.380000e+06,1.570000e+07,70000.000298,1.000000e+05,NaN,NaN,1.936000e+07,8.750000e+06,7.389200e+08,-2.346000e+07,2.270800e+08,862221.0,NaN,NaN,8.344400e+08,7.951200e+08,8.344400e+08,7.951200e+08,NaN,769999.980927,NaN,NaN,4.090000e+06,6.900000e+05,9.800000e+05,1.840000e+06,1.650000e+06,NaN,2.890000e+06,NaN,NaN,NaN,16.5,NaN,1.00362,167650000.0,10.290000
2684,South Africa,ZAF,1991,NaN,NaN,NaN,56.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.1,77.067719,1.05122,NaN,9.570000
3129,South Africa,ZAF,1985,NaN,NaN,NaN,71.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3350,South Africa,ZAF,2006,344890000.0,1250.0,201.0,79.4,0.271382,1.319184,0.761240,14.915405,2.477000e+07,1.366800e+08,1.592000e+07,8.700000e+05,5.323000e+07,1.410000e+06,1.411000e+07,9999.999776,2.500000e+05,NaN,NaN,2.205000e+07,9.030000e+06,6.974600e+08,1.490000e+06,1.405000e+08,NaN,NaN,NaN,8.061500e+08,7.232400e+08,8.061500e+08,7.232400e+08,NaN,600000.023842,NaN,NaN,2.670000e+06,1.610000e+06,7.100000e+05,6.400000e+05,1.160000e+06,NaN,1.710000e+06,NaN,NaN,NaN,16.2,NaN,1.00494,281730000.0,11.310000
3775,South Africa,ZAF,2003,324010000.0,1070.0,186.0,76.0,0.376302,2.141982,1.265050,13.744884,1.325000e+07,1.340300e+08,1.761000e+07,7.000000e+04,2.954000e+07,1.460000e+06,1.559000e+07,NaN,2.700000e+05,NaN,NaN,2.377000e+07,7.770000e+06,6.113500e+08,1.229100e+08,1.061800e+08,NaN,NaN,NaN,8.105300e+08,6.421500e+08,8.105300e+08,6.421500e+08,NaN,NaN,NaN,NaN,NaN,2.160000e+06,6.400000e+05,3.520000e+06,1.130000e+06,NaN,3.400000e+06,NaN,NaN,91.9,14.8,90.579948,1.00903,264880000.0,10.840000
4760,South Africa,ZAF,1993,135040000.0,NaN,NaN,56.0,0.205435,1.328048,1.018826,6.823729,NaN,8.260000e+07,1.800000e+06,2.000000e+04,2.008000e+07,1.600000e+05,1.359000e+07,NaN,1.600000e+05,NaN,NaN,3.787000e+07,4.100000e+06,2.658800e+08,1.937000e+07,6.600000e+07,NaN,NaN,NaN,4.143000e+08,2.704500e+08,4.143000e+08,2.704500e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.940000e+06,2.630000e+06,NaN,NaN,NaN,NaN,NaN,2.8,NaN,NaN,135410000.0,9.880000
4896,South Africa,ZAF,2016,776890000.0,805.0,122.0,36.2,0.409582,2.078512,1.140385,20.998566,1.920000e+07,1.020600e+08,1.018000e+07,2.000000e+05,2.930000e+06,6.000000e+04,7.170000e+06,NaN,1.240000e+06,NaN,NaN,4.950000e+06,9.090000e+06,1.073960e+09,1.658000e+07,4.898700e+08,NaN,NaN,NaN,1.259230e+09,1.180280e+09,1.259230e+09,1.180280e+09,NaN,444175.928831,NaN,1.158230e+06,1.738541e+06,7.704073e+05,1.365764e+06,1.221801e+07,1.412909e+06,NaN,NaN,356940.001249,1.638059e+06,93.7,19.3,87.255333,1.01781,115320000.0,9.590000
4977,South Africa,ZAF,1982,NaN,NaN,NaN,82.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180998.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5036,South Africa,ZAF,2009,865740000.0,1260.0,179.0,59.8,0.371292,1.753095,1.155438,21.280579,1.813000e+07,1.533200e+08,4.670000e+06,3.000000e+05,4.885000e+07,8.900000e+05,3.614000e+07,340000.003576,5.000000e+04,NaN,9999.999776,9.790000e+06,5.130000e+06,1.015330e+09,6.733000e+07,5.237400e+08,NaN,NaN,NaN,1.139790e+09,1.074180e+09,1.139790e+09,1.074180e+09,NaN,620000.004768,NaN,NaN,6.800000e+05,1.420000e+06,1.460000e+06,3.690000e+06,4.040000e+06,NaN,NaN,NaN,NaN,NaN,17.3,NaN,1.00114,186030000.0,10.090000
5095,South Africa,ZAF,2012,862970000.0,1160.0,143.0,40.9,0.276428,1.346907,0.759691,20.173695,1.775000e+07,2.518400e+08,1.330000e+07,7.100000e+05,2.191000e+07,4.400000e+05,-2.937000e+07,19999.999553,6.000000e+04,NaN,NaN,1.667000e+07,7.010000e+06,9.351700e+08,-2.173000e+07,5.040600e+08,919697.0,NaN,NaN,1.104240e+09,1.065830e+09,1.104240e+09,1.065830e+09,NaN,280000.001192,NaN,6.192449e+05,3.427712e+06,4.631871e+05,2.175780e+06,9.892900e+06,1.011155e+06,NaN,NaN,NaN,1.762146e+06,NaN,18.4,NaN,0.99820,201050000.0,10.090000
5624,South Africa,ZAF,1979,NaN,NaN,NaN,97.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6643,South Africa,ZAF,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.1,NaN,NaN,NaN,NaN
6789,South Africa,ZAF,2000,221440000.0,762.0,160.0,71.1,0.367908,2.195773,1.263869,10.896930,4.100000e+06,1.198200e+08,1.979000e+07,1.270000e+06,2.418000e+07,6.100000e+05,1.473000e+07,NaN,1.700000e+05,NaN,NaN,3.236000e+07,5.350000e+06,4.752900e+08,4.264000e+07,1.058500e+08,NaN,NaN,NaN,7.554300e+08,4.900100e+08,7.554300e+08,4.900100e+08,NaN,NaN,NaN,NaN,NaN,3.170000e+06,3.300000e+05,3.720000e+06,1.080000e+06,NaN,2.750000e+06,NaN,NaN,NaN,12.1,81.042252,1.01217,224460000.0,10.720001
6844,South Africa,ZAF,1976,NaN,NaN,NaN,115.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7283,South Africa,ZAF,2002,286250000.0,971.0,177.0,74.4,0.449859,2.696856,1.352065,10.984831,9.870000e+06,1.164700e+08,4.690000e+06,1.010000e+06,4.557000e+07,6.900000e+05,1.748000e+07,NaN,2.010000e+06,NaN,NaN,2.199000e+07,6.110000e+06,4.918200e+08,4.695000e+07,8.944000e+07,788982.0,NaN,NaN,7.611000e+08,5.069600e+08,7.611000e+08,5.069600e+08,NaN,NaN,NaN,NaN,NaN,1.830000e+06,1.490000e+06,2.630000e+06,1.570000e+06,NaN,3.180000e+06,NaN,NaN,NaN,14.1,86.340828,1.01330,220210000.0,10.980000
7588,South Africa,ZAF,2017,851600000.0,738.0,119.0,35.6,0.299292,1.543722,0.877721,17.800639,1.163000e+07,1.246500e+08,1.110000e+07,3.700000e+05,9.300000e+05,1.900000e+05,6.810000e+06,9999.999776,1.360000e+06,NaN,NaN,4.590000e+06,1.470000e+07,9.023600e+08,2.461000e+07,5.960500e+08,727026.0,NaN,NaN,1.051010e+09,1.014810e+09,1.051010e+09,1.014810e+09,NaN,596809.804440,NaN,1.609320e+06,1.651100e+06,6.699559e+05,1.016319e+06,1.541829e+07,1.173110e+06,NaN,NaN,262059.986591,1.918355e+06,NaN,19.4,NaN,1.01267,117980000.0,9.930000
7863,South Africa,ZAF,2013,814920000.0,1110.0,133.0,39.2,0.362623,1.668518,0.936623,24.127572,1.966000e+07,1.654500e+08,1.037000e+07,6.700000e+05,1.027000e+07,3.900000e+05,2.293000e+07,50000.000745,1.460000e+06,NaN,NaN,1.697000e+07,8.890000e+06,1.179170e+09,5.567000e+07,4.768000e+08,NaN,NaN,NaN,1.274420e+09,1.295340e+09,1.274420e+09,1.295340e+09,56709.334254,349999.994040,NaN,8.871990e+05,2.652043e+06,4.064330e+05,1.848494e+06,2.705079e+06,1.197940e+06,NaN,NaN,89778.997004,2.376221e+06,NaN,18.7,NaN,NaN,193070000.0,9.530000
8005,South Africa,ZAF,2015,688860000.0,988.0,125.0,37.1,0.458523,2.137682,1.225838,25.642952,1.296000e+07,2.607800e+08,9.480000e+06,3.600000e+05,2.870000e+06,1.100000e+05,9.730000e+06,59999.998659,1.260000e+06,NaN,NaN,4.430000e+06,1.522000e+07,1.215330e+09,2.918000e+07,3.360500e+08,NaN,NaN,NaN,1.528210e+09,1.420270e+09,1.528210e+09,1.420270e+09,NaN,507742.643356,NaN,9.247500e+05,1.794944e+06,6.173743e+05,1.704248e+06,1.231824e+07,1.812113e+06,NaN,NaN,39406.999946,2.575116e+06,NaN,19.2,90.110489,0.95531,119740000.0,9.430000
8224,South Africa,ZAF,1994,146170000.0,NaN,NaN,57.3,0.213412,1.183479,0.966144,7.225115,7.000000e+04,6.938000e+07,3.090000e+06,3.000000e+04,1.262000e+07,2.700000e+05,1.793000e+07,NaN,4.000000e+04,NaN,NaN,2.973000e+07,6.050000e+06,2.837500e+08,2.386000e+07,7.100000e+07,NaN,NaN,NaN,4.372500e+08,2.930800e+08,4.372500e+08,2.930800e+08,NaN,NaN,NaN,NaN,NaN,NaN,1.600000e+05,5.950000e+06,2.390000e+06,NaN,2.500000e+05,NaN,NaN,NaN,3.9,NaN,1.03220,146910000.0,10.020000
8518,South Africa,ZAF,1977,NaN,NaN,NaN,108.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73316.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8815,South Africa,ZAF,2005,398520000.0,1210.0,201.0,79.1,0.269441,1.442947,0.870110,14.227684,1.817000e+07,1.728800e+08,1.610000e+07,2.620000e+06,5.549000e+07,1.490000e+06,1.439000e+07,19999.999553,6.400000e+05,NaN,NaN,2.287000e+07,7.930000e+06,6.389100e+08,7.026000e+07,1.167800e+08,NaN,NaN,NaN,7.712400e+08,6.812300e+08,7.712400e+08,6.812300e+08,NaN,NaN,NaN,NaN,7.700000e+05,2.290000e+06,5.400000e+05,9.400000e+05,1.350000e+06,NaN,3.130000e+06,19999.999553,NaN,NaN,15.9,NaN,1.00670,249510000.0,11.390000
9033,South Africa,ZAF,1988,NaN,NaN,NaN,61.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9332,South Africa,ZAF,1984,NaN,NaN,NaN,74.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9662,South Africa,ZAF,2008,767050000.0,1270.0,191.0,68.7,0.401295,1.679393,0.906051,22.396984,2.083000e+07,1.640200e+08,3.670000e+06,4.000000e+05,3.626000e+07,1.110000e+06,1.885000e+07,100000.001490,1.500000e+05,NaN,NaN,1.261000e+07,8.340000e+06,1.045970e+09,1.134900e+08,3.786600e+08,NaN,NaN,NaN,1.119380e+09,1.114910e+09,1.119380e+09,1.114910e+09,NaN,330000.013113,NaN,NaN,4.800000e+05,9.600000e+05,1.140000e+06,2.650000e+06,2.830000e+06,NaN,4.800000e+05,NaN,NaN,97.1,16.9,NaN,1.00007,180740000.0,10.200000
9749,South Africa,ZAF,2011,887980000.0,1200.0,161.0,44.8,0.344277,1.701097,1.001295,26.862865,1.719000e+07,3.226400e+08,8.390000e+06,3.800000e+05,3.254000e+07,5.700000e+05,3.817000e+07,29999.999329,7.000000e+04,NaN,19999.999553,1.557000e+07,7.800000e+06,1.349060e+09,4.661000e+07,5.559600e+08,NaN,NaN,NaN,1.389850e+09,1.396970e+09,1.389850e+09,1.396970e+09,NaN,219999.998808,NaN,NaN,2.960000e+06,5.900000e+05,1.620000e+06,1.126000e+07,1.230000e+06,NaN,NaN,600000.023842,1.240000e+06,NaN,18.1,NaN,0.99808,198710000.0,10.140000
9908,South Africa,ZAF,1986,NaN,NaN,NaN,67.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10073,South Africa,ZAF,1998,249380000.0,NaN,NaN,66.8,0.383059,2.080223,1.374145,11.804335,3.550000e+06,8.079000e+07,3.083000e+07,1.010000e+06,4.201000e+07,6.500000e+05,2.199000e+07,NaN,NaN,NaN,NaN,3.111000e+07,1.188000e+07,5.020600e+08,5.412000e+07,8.302000e+07,NaN,NaN,NaN,7.316300e+08,5.156400e+08,7.316300e+08,5.156400e+08,NaN,NaN,NaN,NaN,NaN,3.720000e+06,7.200000e+05,3.270000e+06,1.640000e+06,NaN,1.410000e+06,NaN,NaN,94.2,9.6,84.870483,1.03598,210320000.0,10.490000
10139,South Africa,ZAF,1995,156160000.0,NaN,NaN,59.4,0.253084,1.296023,1.032932,9.319728,5.560000e+06,5.924000e+07,4.340000e+06,1.300000e+05,4.448000e+07,4.100000e+05,2.003000e+07,NaN,8.000000e+04,NaN,NaN,1.960000e+07,8.590000e+06,3.777400e+08,2.393000e+07,1.070000e+08,NaN,NaN,NaN,5.314300e+08,3.861700e+08,5.314300e+08,3.861700e+08,NaN,NaN,NaN,NaN,NaN,3.000000e+04,6.400000e+05,1.880000e+06,2.210000e+06,NaN,6.600000e+05,NaN,NaN,89.0,5.3,NaN,NaN,211570000.0,10.150000
10140,South Africa,ZAF,2004,367420000.0,1150.0,195.0,78.1,0.281618,1.496252,0.950892,13.355646,1.467000e+07,1.433000e+08,1.883000e+07,1.870000e+06,5.565000e+07,1.240000e+06,1.594000e+07,NaN,4.000000e+05,NaN,NaN,2.558000e+07,7.030000e+06,6.025700e+08,8.706000e+07,9.466000e+07,NaN,NaN,NaN,7.267200e+08,6.316100e+08,7.267200e+08,6.316100e+08,NaN,NaN,NaN,NaN,NaN,3.060000e+06,3.200000e+05,2.710000e+06,1.120000e+06,NaN,3.020000e+06,NaN,NaN,91.9,15.4,95.654922,1.00831,238170000.0,10.600000
10141,South Africa,ZAF,1980,NaN,NaN,NaN,92.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10209,South Africa,ZAF,2010,834180000.0,1230.0,171.0,51.2,0.282097,1.414861,0.896421,20.232944,1.533000e+07,1.531100e+08,7.110000e+06,3.600000e+05,3.605000e+07,1.030000e+06,2.474000e+07,29999.999329,5.000000e+04,NaN,19999.999553,1.430000e+07,7.450000e+06,9.711200e+08,3.929000e+07,5.256700e+08,NaN,NaN,NaN,1.099420e+09,1.036270e+09,1.099420e+09,1.036270e+09,NaN,779999.971390,NaN,NaN,1.490000e+06,6.600000e+05,1.670000e+06,3.660000e+06,1.160000e+06,NaN,NaN,NaN,NaN,NaN,17.7,NaN,1.00054,173470000.0,10.300000
10443,South Africa,ZAF,1989,NaN,NaN,NaN,59.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.04037,NaN,NaN
10953,South Africa,ZAF,1974,NaN,NaN,NaN,128.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11028,South Africa,ZAF,1981,NaN,NaN,NaN,87.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11908,South Africa,ZAF,1962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,106550.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
px.scatter(aids[aids['Primary completion rate, total (% of relevant age group)']<=1500000000],
           x='Primary completion rate, total (% of relevant age group)', 
           y='Prevalence of HIV, total (% of population ages 15-49)')

In [47]:
gender.columns=[remove_avg(col) for col in gender.columns]

In [48]:
gender

,Country Name,Country Code,Year,"Adjusted net enrollment rate, primary, female (% of primary school age children)","Adjusted net enrollment rate, primary, male (% of primary school age children)","Adolescent fertility rate (births per 1,000 women ages 15-19)",Births attended by skilled health staff (% of total),"Children out of school, primary, female","Children out of school, primary, male","Educational attainment, Doctoral or equivalent, population 25+, female (%) (cumulative)","Educational attainment, Doctoral or equivalent, population 25+, male (%) (cumulative)","Educational attainment, Doctoral or equivalent, population 25+, total (%) (cumulative)","Educational attainment, at least Bachelor's or equivalent, population 25+, female (%) (cumulative)","Educational attainment, at least Bachelor's or equivalent, population 25+, male (%) (cumulative)","Educational attainment, at least Bachelor's or equivalent, population 25+, total (%) (cumulative)","Educational attainment, at least completed lower secondary, population 25+, female (%) (cumulative)","Educational attainment, at least completed lower secondary, population 25+, male (%) (cumulative)","Educational attainment, at least completed lower secondary, population 25+, total (%) (cumulative)","Educational attainment, at least completed post-secondary, population 25+, female (%) (cumulative)","Educational attainment, at least completed post-secondary, population 25+, male (%) (cumulative)","Educational attainment, at least completed post-secondary, population 25+, total (%) (cumulative)","Educational attainment, at least completed short-cycle tertiary, population 25+, female (%) (cumulative)","Educational attainment, at least completed short-cycle tertiary, population 25+, male (%) (cumulative)","Educational attainment, at least completed short-cycle tertiary, population 25+, total (%) (cumulative)","Educational attainment, at least completed upper secondary, population 25+, female (%) (cumulative)","Educational attainment, at least completed upper secondary, population 25+, male (%) (cumulative)","Educational attainment, at least completed upper secondary, population 25+, total (%) (cumulative)","Fertility rate, total (births per woman)","Life expectancy at birth, female (years)","Life expectancy at birth, male (years)","Mortality rate, adult, female (per 1,000 female adults)","Mortality rate, adult, male (per 1,000 male adults)","Persistence to last grade of primary, female (% of cohort)","Persistence to last grade of primary, male (% of cohort)","Primary education, teachers (% female)","Progression to secondary school, female (%)","Progression to secondary school, male (%)","Repeaters, primary, female (% of female enrollment)","Repeaters, primary, male (% of male enrollment)","School enrollment, secondary, female (% gross)","School enrollment, secondary, female (% net)","School enrollment, secondary, male (% gross)","School enrollment, secondary, male (% net)","School enrollment, tertiary, female (% gross)","School enrollment, tertiary, male (% gross)","Secondary education, general pupils (% female)","Secondary education, pupils (% female)","Secondary education, teachers (% female)","Secondary education, vocational pupils (% female)","Survival to age 65, female (% of cohort)","Survival to age 65, male (% of cohort)","Trained teachers in primary education, female (% of female teachers)","Trained teachers in primary education, male (% of male teachers)"
0,Africa Eastern and Southern,AFE,1987,NaN,NaN,133.152267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.447606,53.116147,49.545128,321.456381,399.222922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.535395,41.856181,NaN,NaN
1,Albania,ALB,1977,NaN,NaN,25.405000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.966000,71.046000,67.943000,108.946000,144.162000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79.087492,73.363800,NaN,NaN
2,Albania,ALB,2019,NaN,NaN,19.502800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.597000,80.201000,77.002000,49.088000,92.179000,NaN,NaN,85.334419,NaN,NaN,NaN,NaN,95.659927,NaN,94.585167,NaN,73.340530,46.944038,NaN,NaN,67.172157,NaN,91.299750,85.085853,NaN,NaN
3,Armenia,ARM,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Azerbaijan,AZE,2013,91.82654,95.28533,50.559600,99.9,8359.0,185.0,0.0,0.0,0.0,12.5984,18.998341,15.66057,93.847771,97.492172,95.591499,26.129259,34.288342,30.033131,23.58526,27.33567,25.379709,85.48262,92.240837,88.716209,1.980000,74.683000,68.840000,88.155000,171.228000,99.907204,95.052818,90.197990,100.0,98.29169,0.23481,0.2200,NaN,NaN,NaN,NaN,22.623819,20.329540,45.87309,NaN,NaN,NaN,82.982853,71.209068,99.570183,99.552238
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15546,Tonga,TON,1997,NaN,NaN,22.503000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.340000,70.083000,68.787000,141.823000,184.383000,NaN,NaN,70.075760,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.605360,69.725389,NaN,NaN
15547,St. Vincent and the Grenadines,VCT,1999,NaN,NaN,71.527800,99.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.442000,72.662000,68.911000,156.942000,211.148000,NaN,NaN,70.019920,NaN,NaN,7.87911,10.2133,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.296767,68.511693,69.132294,59.136211
15548,Vietnam,VNM,1996,NaN,NaN,30.560800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.529000,76.894000,67.464000,83.479000,203.332000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.150107,68.423600,NaN,NaN
15549,Kosovo,XKX,1977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15550,"Yemen, Rep.",YEM,1970,NaN,NaN,182.256200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.386000,38.078000,35.601000,391.701000,452.841000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.015937,26.443085,NaN,NaN

In [195]:
social_dev

,Country Name,Country Code,Year,"Adolescent fertility rate (births per 1,000 women ages 15-19)","Children in employment, female (% of female children ages 7-14)","Children in employment, male (% of male children ages 7-14)","Children in employment, study and work (% of children in employment, ages 7-14)","Children in employment, study and work, female (% of female children in employment, ages 7-14)","Children in employment, study and work, male (% of male children in employment, ages 7-14)","Children in employment, total (% of children ages 7-14)","Children in employment, work only (% of children in employment, ages 7-14)","Children in employment, work only, female (% of female children in employment, ages 7-14)","Children in employment, work only, male (% of male children in employment, ages 7-14)","Labor force participation rate for ages 15-24, female (%) (modeled ILO estimate)","Labor force participation rate for ages 15-24, male (%) (modeled ILO estimate)","Labor force participation rate for ages 15-24, total (%) (modeled ILO estimate)","Labor force participation rate, female (% of female population ages 15+) (modeled ILO estimate)","Labor force participation rate, female (% of female population ages 15-64) (modeled ILO estimate)","Labor force participation rate, male (% of male population ages 15+) (modeled ILO estimate)","Labor force participation rate, male (% of male population ages 15-64) (modeled ILO estimate)","Labor force participation rate, total (% of total population ages 15-64) (modeled ILO estimate)","Life expectancy at birth, female (years)","Life expectancy at birth, male (years)","Literacy rate, youth (ages 15-24), gender parity index (GPI)","Prevalence of HIV, female (% ages 15-24)","Prevalence of HIV, male (% ages 15-24)",Proportion of seats held by women in national parliaments (%),Refugee population by country or territory of asylum,Refugee population by country or territory of origin,"School enrollment, primary (gross), gender parity index (GPI)","School enrollment, primary and secondary (gross), gender parity index (GPI)","School enrollment, secondary (gross), gender parity index (GPI)","School enrollment, tertiary (gross), gender parity index (GPI)","Unemployment, female (% of female labor force) (modeled ILO estimate)","Unemployment, male (% of male labor force) (modeled ILO estimate)","Vulnerable employment, female (% of female employment) (modeled ILO estimate)","Vulnerable employment, male (% of male employment) (modeled ILO estimate)"
0,Afghanistan,AFG,1990,162.835400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.23,64.26,40.11,15.32,15.83,79.16,81.01,49.07,51.442000,49.281000,NaN,0.1,0.1,NaN,50.0,6339095.0,0.54850,NaN,NaN,0.47453,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,1994,164.448600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.30,63.71,40.19,15.36,15.88,78.63,80.56,49.41,54.012000,51.746000,NaN,0.1,0.1,NaN,19134.0,2731166.0,0.50580,0.43200,0.28143,NaN,14.76,11.09,98.600003,90.540001
2,Africa Western and Central,AFW,1969,172.026085,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.162546,39.712956,NaN,NaN,NaN,NaN,131200.0,71050.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Western and Central,AFW,1989,156.266617,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.040823,47.437250,NaN,NaN,NaN,NaN,132129.0,199380.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,1973,224.736000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.449000,40.716000,NaN,NaN,NaN,NaN,NaN,426550.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15405,San Marino,SMR,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.96996,1.08121,1.20937,NaN,NaN,NaN,NaN,NaN
15406,Tanzania,TZA,1961,157.680000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.116000,42.600000,NaN,NaN,NaN,NaN,12000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15407,Tanzania,TZA,1971,155.826200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.375000,45.992000,NaN,NaN,NaN,NaN,71240.0,NaN,0.65777,0.64500,0.41462,0.20924,NaN,NaN,NaN,NaN
15408,Uganda,UGA,1963,173.056000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.647000,44.719000,NaN,NaN,NaN,NaN,59000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15409,Uganda,UGA,2007,150.734000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.50,58.15,55.27,65.46,66.66,76.44,76.91,71.64,55.764000,51.926000,NaN,4.6,1.7,30.722892,228956.0,21325.0,0.99436,0.96106,0.79395,NaN,2.88,2.21,89.010000,74.810000

In [51]:
social_dev.columns=[remove_avg(col) for col in social_dev.columns]

Refugees bring social unrest to the country accepting them

In [205]:
social_dev_1=social_dev.copy()
social_dev_1['high_HIV']=(social_dev_1['Prevalence of HIV, female (% ages 15-24)']>0.1) \
                        & (social_dev_1['Prevalence of HIV, male (% ages 15-24)']>0.1)
px.line(social_dev_1[['high_HIV','Year','Refugee population by country or territory of asylum']]
        .groupby(['high_HIV','Year']).mean().reset_index(),
        x='Year', y='Refugee population by country or territory of asylum', color='high_HIV',
        labels={'Refugee population by country or territory of asylum': 'Refuegee Population'}, 
        title="Average refugees' population accross years")

In [200]:
social_dev_2=social_dev.copy()
social_dev_2['many_refugee']=social_dev_2['Refugee population by country or territory of asylum']>=social_dev['Refugee population by country or territory of asylum'].median()
social_dev_2['avg_life_expect']=(social_dev_2['Life expectancy at birth, female (years)']+social_dev_2['Life expectancy at birth, male (years)'])/2
px.bar(social_dev_2[['many_refugee', 'avg_life_expect']].groupby('many_refugee').mean().reset_index(),
        x='many_refugee', y='avg_life_expect', color='many_refugee',
        title='Average Life Expectancy in Countries with or without many refugees')

In [146]:
summary=social_dev['Refugee population by country or territory of asylum'].describe()
def map_summary(num):
    if num==np.nan:
        return num
    if num<summary['25%']:
        return 'Low'
    elif num<summary['50%']:
        return 'Normal'
    elif num<summary['75%']:
        return 'High'
    return 'Very high'

In [203]:
social_dev_3=social_dev_2.copy()
social_dev_3['refugee_popu_level']=social_dev_3['Refugee population by country or territory of asylum'].apply(map_summary)
px.bar(social_dev_3[['refugee_popu_level', 'avg_life_expect']].groupby('refugee_popu_level').mean().reset_index(),
        x='refugee_popu_level', y='avg_life_expect', color='refugee_popu_level', 
        range_y=[60, 69], 
        category_orders={'refugee_popu_level': ['Low', 'Normal', 'High', 'Very high']},
        title='Average Life expectancy in countries with different refugee population level',
        color_discrete_sequence=['#c0dee5', '#61a4ad', '#07575b', '#003b46'])

In [201]:
social_dev_4=social_dev_3.copy()
social_dev_4.rename(columns={'Literacy rate, youth (ages 15-24), gender parity index (GPI)': 'literacy_rate',
                             'Refugee population by country or territory of origin': 'Refugee population'}, inplace=True)
social_dev_5=social_dev_4[social_dev_4['literacy_rate']<=1].groupby('Country Code')[['literacy_rate', 'Refugee population']].mean().dropna().sort_values(by='Refugee population')
social_dev_5=social_dev_5[social_dev_5['literacy_rate']<=1]
partial=pd.concat([social_dev_5.head(3).assign(category='top 3'), social_dev_5.tail(3).assign(category='bottom 3')])
px.bar(partial.reset_index(), x='Country Code', y='literacy_rate',
        color='category', text_auto=True, title='Literacy rate in top 3 and bottom 3 countries in terms of refugee population')

In [ ]:
social_dev_f = social_dev[['Country Name', 'Country Code', 'Year', 
                           'Prevalence of HIV, female (% ages 15-24)', 
                           'Prevalence of HIV, male (% ages 15-24)',
                           'Refugee population by country or territory of asylum', 
                           'Refugee population by country or territory of origin']]

In [208]:
social_dev_f['Refugee population'] = social_dev_f['Refugee population by country or territory of asylum'] + social_dev_f['Refugee population by country or territory of origin']

/var/folders/s9/b35x2lvd0zl66546s25wwsjc0000gn/T/ipykernel_95860/3422875220.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [268]:
social_dev_f[social_dev_f['Country Code']=='LTE'].groupby('Country Code').last()

,Country Name,Year,"Prevalence of HIV, female (% ages 15-24)","Prevalence of HIV, male (% ages 15-24)",Refugee population by country or territory of asylum,Refugee population by country or territory of origin,Refugee population
Country Code,,,,,,,
LTE,Late-demographic dividend,2007,NaN,NaN,1150267.0,1544449.0,2694716.0

In [280]:
modify = social_dev_f[~(social_dev_f['Country Code'].isin(['WLD', 'IBT', 'LMY', 'IDA', 'MIC', 
                                                           'FCS', 'IDX', 'EAR', 'HPC', 'TMN', 
                                                           'ARB', 'LIC', 'MNA', 'SSA', 'PRE',
                                                           'ECS', 'HIC', 'TSS', 'AFE', 'OED',
                                                           'LDC', 'MEA', 'UMC', 'SSF', 'IBD', 
                                                           'LMC', 'SAS', 'TSA', 'LTE', 'PST', 
                                                           'TEC', 'IDB', 'ECA', 'AFW']))]

In [336]:
modify.groupby('Country Code').agg({'Country Name' : 'last', 'Refugee population by country or territory of asylum' : ['max', 'mean', 'sum']}).reset_index()\
    .sort_values(by=('Refugee population by country or territory of asylum', 'mean'), ascending=False)

    Country Code                    Country Name  \
                                            last
159          PAK                        Pakistan
67           EUU                  European Union
97           IRN              Iran, Islamic Rep.
103          JOR                          Jordan
62           EMU                       Euro area
..           ...                             ...
211          TUV                          Tuvalu
218          VCT  St. Vincent and the Grenadines
220          VGB          British Virgin Islands
221          VIR           Virgin Islands (U.S.)
225          XKX                          Kosovo

    Refugee population by country or territory of asylum                \
                                                     max          mean
159                                          3275715.0    1.828176e+06
67                                           2657199.0    1.616758e+06
97                                           4404995.0    1.536688e+06
103                                          3009517.0    1.364275e+06
62                                           2335623.0    1.353054e+06
..                                                 ...             ...
211                                                NaN             NaN
218                                                NaN             NaN
220                                                NaN             NaN
221                                                NaN             NaN
225                                                NaN             NaN


            sum
159  76783395.0
67   50119513.0
97   70687660.0
103  83220785.0
62   41944685.0
..          ...
211         0.0
218         0.0
220         0.0
221         0.0
225         0.0

[230 rows x 5 columns]

In [350]:
final = modify.copy()
final['is_SF'] = final['Country Code'] == 'ZAF'

support

In [375]:
px.line(final[(final['Year']>=2000) & (final['Country Code'].isin(['NAM', 'BWA', 'ZWE', 'MOZ', 'SWZ', 'LSO', 'ZAF']))]\
        .groupby(['is_SF', 'Year'])[['Prevalence of HIV, male (% ages 15-24)']].mean().reset_index(),
         x = 'Year', y = 'Prevalence of HIV, male (% ages 15-24)', color='is_SF')

against

In [367]:
px.line(final[(final['Country Code'].isin(['NAM', 'BWA', 'ZWE', 'MOZ', 'SWZ', 'LSO', 'ZAF']))&\
               (final['Year']>=2000)]\
        .dropna(subset=['Refugee population'], inplace=False).sort_values(by='Year'), 
        x='Year', y='Refugee population by country or territory of asylum', color='Country Code')

In [366]:
final['hiv/ref ratio'] = final['Prevalence of HIV, female (% ages 15-24)']*final['Refugee population by country or territory of asylum']
px.line(final[(final['Country Code'].isin(['NAM', 'BWA', 'ZWE', 'MOZ', 'SWZ', 'LSO', 'ZAF']))&\
              (final['Year'] >= 1995)].dropna(subset=['hiv/ref ratio'], inplace=False).sort_values(by='Year'), 
        x='Year', y='hiv/ref ratio', color='Country Code')

In [391]:
countries = ['NAM', 'BWA', 'ZWE', 'MOZ', 'SWZ', 'LSO', 'ZAF']
color_map={country : 'green' for country in countries}
color_map['ZAF'] = 'red'
px.line(final[(final['Country Code'].isin(countries))&\
              (final['Year'] >= 2000)].dropna(subset=['Prevalence of HIV, male (% ages 15-24)'], inplace=False).sort_values(by='Year'), 
        x='Year', y='Prevalence of HIV, male (% ages 15-24)', color='Country Code',
        color_discrete_map = color_map)

In [ ]:
def zscore(s):
    return (s-s.mean())/s.std()

In [398]:
null_per=(social_dev.isnull().sum() / len(social_dev)).sort_values()
null_per[null_per<0.7].index

Index(['Country Name', 'Country Code', 'Year',
       'Life expectancy at birth, male (years)',
       'Life expectancy at birth, female (years)',
       'Adolescent fertility rate (births per 1,000 women ages 15-19)',
       'School enrollment, primary (gross), gender parity index (GPI)',
       'Refugee population by country or territory of asylum',
       'School enrollment, secondary (gross), gender parity index (GPI)',
       'School enrollment, primary and secondary (gross), gender parity index (GPI)',
       'Refugee population by country or territory of origin',
       'Labor force participation rate, total (% of total population ages 15-64) (modeled ILO estimate)',
       'Labor force participation rate, male (% of male population ages 15-64) (modeled ILO estimate)',
       'Labor force participation rate, female (% of female population ages 15-64) (modeled ILO estimate)',
       'Labor force participation rate, female (% of female population ages 15+) (modeled ILO estimate)',
       'Labor force participation rate, male (% of male population ages 15+) (modeled ILO estimate)',
       'Labor force participation rate for ages 15-24, male (%) (modeled ILO estimate)',
       'Labor force participation rate for ages 15-24, female (%) (modeled ILO estimate)',
       'Labor force participation rate for ages 15-24, total (%) (modeled ILO estimate)',
       'School enrollment, tertiary (gross), gender parity index (GPI)',
       'Unemployment, male (% of male labor force) (modeled ILO estimate)',
       'Unemployment, female (% of female labor force) (modeled ILO estimate)',
       'Vulnerable employment, male (% of male employment) (modeled ILO estimate)',
       'Vulnerable employment, female (% of female employment) (modeled ILO estimate)',
       'Proportion of seats held by women in national parliaments (%)',
       'Prevalence of HIV, female (% ages 15-24)',
       'Prevalence of HIV, male (% ages 15-24)'],
      dtype='object')

In [414]:
to_stand = ['Life expectancy at birth, male (years)',
       'Life expectancy at birth, female (years)',
       'Adolescent fertility rate (births per 1,000 women ages 15-19)',
       'School enrollment, primary (gross), gender parity index (GPI)',
       'School enrollment, secondary (gross), gender parity index (GPI)',
       'School enrollment, primary and secondary (gross), gender parity index (GPI)',
       'Refugee population by country or territory of origin',
       'Labor force participation rate, total (% of total population ages 15-64) (modeled ILO estimate)',
       'Labor force participation rate, male (% of male population ages 15-64) (modeled ILO estimate)',
       'Labor force participation rate, female (% of female population ages 15-64) (modeled ILO estimate)',
       'Labor force participation rate, female (% of female population ages 15+) (modeled ILO estimate)',
       'Labor force participation rate, male (% of male population ages 15+) (modeled ILO estimate)',
       'Labor force participation rate for ages 15-24, male (%) (modeled ILO estimate)',
       'Labor force participation rate for ages 15-24, female (%) (modeled ILO estimate)',
       'Labor force participation rate for ages 15-24, total (%) (modeled ILO estimate)',
       'School enrollment, tertiary (gross), gender parity index (GPI)',
       'Unemployment, male (% of male labor force) (modeled ILO estimate)',
       'Unemployment, female (% of female labor force) (modeled ILO estimate)',
       'Vulnerable employment, male (% of male employment) (modeled ILO estimate)',
       'Vulnerable employment, female (% of female employment) (modeled ILO estimate)',
       'Proportion of seats held by women in national parliaments (%)',
       'Prevalence of HIV, female (% ages 15-24)',
       'Prevalence of HIV, male (% ages 15-24)']
final_std=social_dev[~(social_dev['Country Code'].isin(['WLD', 'IBT', 'LMY', 'IDA', 'MIC', 
                                                           'FCS', 'IDX', 'EAR', 'HPC', 'TMN', 
                                                           'ARB', 'LIC', 'MNA', 'SSA', 'PRE',
                                                           'ECS', 'HIC', 'TSS', 'AFE', 'OED',
                                                           'LDC', 'MEA', 'UMC', 'SSF', 'IBD', 
                                                           'LMC', 'SAS', 'TSA', 'LTE', 'PST', 
                                                           'TEC', 'IDB', 'ECA', 'AFW']))].copy()[to_stand]

for col in final_std.columns:
    final_std[col] = zscore(final_std[col])
final_std

,"Life expectancy at birth, male (years)","Life expectancy at birth, female (years)","Adolescent fertility rate (births per 1,000 women ages 15-19)","School enrollment, primary (gross), gender parity index (GPI)","School enrollment, secondary (gross), gender parity index (GPI)","School enrollment, primary and secondary (gross), gender parity index (GPI)",Refugee population by country or territory of origin,"Labor force participation rate, total (% of total population ages 15-64) (modeled ILO estimate)","Labor force participation rate, male (% of male population ages 15-64) (modeled ILO estimate)","Labor force participation rate, female (% of female population ages 15-64) (modeled ILO estimate)","Labor force participation rate, female (% of female population ages 15+) (modeled ILO estimate)","Labor force participation rate, male (% of male population ages 15+) (modeled ILO estimate)","Labor force participation rate for ages 15-24, male (%) (modeled ILO estimate)","Labor force participation rate for ages 15-24, female (%) (modeled ILO estimate)","Labor force participation rate for ages 15-24, total (%) (modeled ILO estimate)","School enrollment, tertiary (gross), gender parity index (GPI)","Unemployment, male (% of male labor force) (modeled ILO estimate)","Unemployment, female (% of female labor force) (modeled ILO estimate)","Vulnerable employment, male (% of male employment) (modeled ILO estimate)","Vulnerable employment, female (% of female employment) (modeled ILO estimate)",Proportion of seats held by women in national parliaments (%),"Prevalence of HIV, female (% ages 15-24)","Prevalence of HIV, male (% ages 15-24)"
0,-1.200952,-1.312110,1.649400,-2.777551,NaN,NaN,15.893995,-1.774497,0.333412,-2.363595,-2.248063,0.607797,0.774924,-1.574224,-0.511244,-1.112456,NaN,NaN,NaN,NaN,NaN,-0.381543,-0.398061
1,-0.972556,-1.094860,1.679589,-3.088986,-2.826616,-3.382363,6.707069,-1.741667,0.273981,-2.360649,-2.245530,0.545688,0.735117,-1.570017,-0.505446,NaN,0.660314,0.747795,2.002144,1.766745,NaN,-0.381543,-0.398061
4,-1.994547,-1.987783,2.807798,NaN,NaN,NaN,0.838788,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,0.665687,0.512367,0.074927,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1.358102,1.321771,-1.225150,0.498506,0.972883,1.011997,-0.247195,-0.023894,-0.653157,0.282759,-0.258823,-1.539044,-1.235716,-0.564743,-0.968586,0.774242,-0.176311,-0.226502,-1.025601,-1.049987,1.622804,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15405,NaN,NaN,NaN,0.296401,1.249817,0.967441,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15406,-1.819984,-1.846866,1.552923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15407,-1.505696,-1.571373,1.518231,-1.980581,-2.241513,-1.955232,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.793698,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15408,-1.623647,-1.632913,1.840667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15409,-0.955878,-0.946758,1.422937,0.474365,-0.575120,0.162418,-0.193043,0.404824,-0.208078,0.630933,0.927375,0.289052,0.332699,0.725349,0.587535,NaN,-0.947745,-0.868776,1.402617,1.466373,1.208829,1.073581,1.120882

In [427]:
negative = ['Adolescent fertility rate (births per 1,000 women ages 15-19)',
            'Refugee population by country or territory of origin',
            'Unemployment, male (% of male labor force) (modeled ILO estimate)',
            'Unemployment, female (% of female labor force) (modeled ILO estimate)',
            'Vulnerable employment, male (% of male employment) (modeled ILO estimate)',
            'Vulnerable employment, female (% of female employment) (modeled ILO estimate)',
            'Prevalence of HIV, female (% ages 15-24)',
            'Prevalence of HIV, male (% ages 15-24)']
for col in negative:
    final_std[col] = -final_std[col]

In [432]:
final['social quality'] = final_std.mean(axis=1)

In [433]:
countries = ['NAM', 'BWA', 'ZWE', 'MOZ', 'SWZ', 'LSO', 'ZAF']
color_map={country : 'green' for country in countries}
color_map['ZAF'] = 'red'
px.line(final[(final['Country Code'].isin(countries))&\
              (final['Year'])].sort_values(by='Year'), 
        x='Year', y='social quality', color='Country Code',
        color_discrete_map = color_map)

In [435]:
px.line(final[(final['Year']<=2019) & (final['Country Code'].isin(['NAM', 'BWA', 'ZWE', 'MOZ', 'SWZ', 'LSO', 'ZAF']))]\
        .groupby(['is_SF', 'Year'])[['social quality']].mean().reset_index(),
         x = 'Year', y = 'social quality', color='is_SF')

In [510]:
final[final['Country Code']=='PAK']

,Country Name,Country Code,Year,"Prevalence of HIV, female (% ages 15-24)","Prevalence of HIV, male (% ages 15-24)",Refugee population by country or territory of asylum,Refugee population by country or territory of origin,Refugee population,is_SF,hiv/ref ratio,social quality,log quality,is_AFG,std quality,period,is_PAK,is_IRN
196,Pakistan,PAK,1978,NaN,NaN,NaN,NaN,NaN,False,NaN,-1.776741,0.574781,False,-2.117002,70s,True,False
487,Pakistan,PAK,2001,0.1,0.1,2198792.0,12326.0,2211118.0,False,219879.2,-0.242307,-1.417551,False,-0.154763,00s,True,False
1161,Pakistan,PAK,2002,0.1,0.1,1227429.0,23164.0,1250593.0,False,122742.9,-0.183366,-1.696273,False,-0.079389,00s,True,False
1542,Pakistan,PAK,1971,NaN,NaN,NaN,NaN,NaN,False,NaN,-2.159689,0.769964,False,-2.606717,70s,True,False
1609,Pakistan,PAK,2007,0.1,0.1,2035025.0,31847.0,2066872.0,False,203502.5,-0.209848,-1.561370,False,-0.113255,00s,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14369,Pakistan,PAK,2006,0.1,0.1,1044464.0,25636.0,1070100.0,False,104446.4,-0.218284,-1.521958,False,-0.124043,00s,True,False
14444,Pakistan,PAK,2014,0.1,0.1,1505521.0,335947.0,1841468.0,False,150552.1,-0.189440,-1.663683,False,-0.087157,10s,True,False
14685,Pakistan,PAK,1983,NaN,NaN,2901360.0,NaN,NaN,False,NaN,-1.736470,0.551854,False,-2.065503,80s,True,False
15077,Pakistan,PAK,1993,0.1,0.1,1479266.0,1420.0,1480686.0,False,147926.6,-0.254377,-1.368938,False,-0.170199,90s,True,False
15239,Pakistan,PAK,1990,0.1,0.1,3255975.0,485.0,3256460.0,False,325597.5,-0.775323,-0.254475,False,-0.836386,90s,True,False

Support

In [514]:
final['is_PAK'] = final['Country Code'] == 'PAK'
is_AFG = final[final['Country Code'] == 'PAK'].sort_values(by='Year')
percent = final[final['Country Code'] != 'PAK'].groupby('Year')[['social quality']]\
    .quantile([0.25, 0.75]).unstack().reset_index().sort_values(by='Year')
percent.columns = ['year', 'p25', 'p75']

fig = go.Figure()
fig.add_trace(go.Scatter(x=is_AFG['Year'], y=is_AFG['social quality'],
                          name='social quality of PAK',
                          line=dict(color='red')))
fig.add_trace(go.Scatter(x=percent['year'], y=percent['p75'],
                         name='75 Percentile of social quality each year',
                         line=dict(color='rgba(0,0,255,0.2)'),
                        showlegend=False,
                        hoverinfo='skip'))
fig.add_trace(go.Scatter(x=percent['year'], y=percent['p25'],
                         name='Interquartile Range of social quality',
                         fill='tonexty',
                        fillcolor='rgba(200,200,200,0.7)',
                        line=dict(color='rgba(0,0,255,0.2)'),
                        showlegend=True))
fig.update_layout(
    title='Social Quality of Afghanistan vs. the rest of the World',
    xaxis_title='Year',
    yaxis_title='Social Quality'
)
fig.show()

In [475]:
final['Year'].min()

np.int64(1960)

In [471]:
final['social quality'].max()

np.float64(4.854486378805403)

In [476]:
def period(year):
    if year<1970:
        return '60s'
    elif year<1980:
        return '70s'
    elif year<1990:
        return '80s'
    elif year<2000:
        return '90s'
    elif year<2010:
        return '00s'
    elif year<2020:
        return '10s'
    return '20s'

In [477]:
final['period'] = final['Year'].apply(period)

In [483]:
final['log quality'] = final['social quality'].apply(lambda x: abs(x)).apply(np.log)

In [488]:
final[(final['is_AFG']) & (final['Year'] >= 2000)]

,Country Name,Country Code,Year,"Prevalence of HIV, female (% ages 15-24)","Prevalence of HIV, male (% ages 15-24)",Refugee population by country or territory of asylum,Refugee population by country or territory of origin,Refugee population,is_SF,hiv/ref ratio,social quality,log quality,is_AFG,std quality,period
300,Afghanistan,AFG,2007,0.1,0.1,43.0,3057655.0,3057698.0,False,4.3,-1.217293,0.196629,True,-1.401578,00s
952,Afghanistan,AFG,2015,0.1,0.1,257553.0,2666294.0,2923847.0,False,25755.3,-1.004369,0.004359,True,-1.129290,10s
3783,Afghanistan,AFG,2010,0.1,0.1,6434.0,3054699.0,3061133.0,False,643.4,-1.129670,0.121925,True,-1.289526,10s
5860,Afghanistan,AFG,2017,0.1,0.1,75927.0,2624265.0,2700192.0,False,7592.7,-0.969862,-0.030601,True,-1.085164,10s
6033,Afghanistan,AFG,2001,0.1,0.1,10.0,3809763.0,3809773.0,False,1.0,-1.943579,0.664531,True,-2.330356,00s
6630,Afghanistan,AFG,2012,0.1,0.1,16184.0,2586132.0,2602316.0,False,1618.4,-1.011675,0.011608,True,-1.138634,10s
7619,Afghanistan,AFG,2011,0.1,0.1,3011.0,2664423.0,2667434.0,False,301.1,-1.056709,0.055159,True,-1.196223,10s
7934,Afghanistan,AFG,2013,0.1,0.1,16861.0,2556483.0,2573344.0,False,1686.1,-1.007570,0.007542,True,-1.133384,10s
9734,Afghanistan,AFG,2019,0.1,0.1,72227.0,2727556.0,2799783.0,False,7222.7,-0.825636,-0.191601,True,-0.900726,10s
9899,Afghanistan,AFG,2014,0.1,0.1,300421.0,2596259.0,2896680.0,False,30042.1,-1.027256,0.026891,True,-1.158558,10s
9900,Afghanistan,AFG,2016,0.1,0.1,59770.0,2501447.0,2561217.0,False,5977.0,-0.968728,-0.031771,True,-1.083713,10s
9971,Afghanistan,AFG,2020,0.1,0.1,72278.0,2594774.0,2667052.0,False,7227.8,-1.176043,0.162155,True,-1.348828,20s
10051,Afghanistan,AFG,2006,0.1,0.1,34.0,2107510.0,2107544.0,False,3.4,-1.110973,0.105236,True,-1.265616,00s
10131,Afghanistan,AFG,2005,0.1,0.1,31.0,2166139.0,2166170.0,False,3.1,-1.153932,0.143175,True,-1.320552,00s
10375,Afghanistan,AFG,2000,0.1,0.1,NaN,3587327.0,NaN,False,NaN,-1.584903,0.460523,True,-1.871680,00s
10840,Afghanistan,AFG,2003,0.1,0.1,24.0,2136039.0,2136063.0,False,2.4,-1.290108,0.254726,True,-1.494694,00s
13328,Afghanistan,AFG,2008,0.1,0.1,37.0,2833116.0,2833153.0,False,3.7,-1.157504,0.146266,True,-1.325120,00s
13566,Afghanistan,AFG,2002,0.1,0.1,NaN,2510294.0,NaN,False,NaN,-1.242264,0.216935,True,-1.433511,00s
14556,Afghanistan,AFG,2018,0.1,0.1,72228.0,2681267.0,2753495.0,False,7222.8,-1.077311,0.074468,True,-1.222569,10s
15261,Afghanistan,AFG,2004,0.1,0.1,31.0,2414460.0,2414491.0,False,3.1,-1.424968,0.354149,True,-1.667154,00s
15262,Afghanistan,AFG,2009,0.1,0.1,36.0,2887114.0,2887150.0,False,3.6,-1.162895,0.150913,True,-1.332014,00s

In [506]:
px.bar(final.groupby(['is_PAK', 'period'])['log quality'].mean().reset_index(),
        x='period', y='log quality', color='is_PAK', barmode='group')

In [490]:
final['is_AFG'] = final['Country Code'] == 'AFG'
is_AFG = final[final['Country Code'] == 'AFG'].sort_values(by='Year')
percent = final[final['Country Code'] != 'AFG'].groupby('Year')[['log quality']]\
    .quantile([0.25, 0.75]).unstack().reset_index().sort_values(by='Year')
percent.columns = ['year', 'p25', 'p75']

fig = go.Figure()
fig.add_trace(go.Scatter(x=is_AFG['Year'], y=is_AFG['log quality'],
                          name='social quality of Afghanistan',
                          line=dict(color='red')))
fig.add_trace(go.Scatter(x=percent['year'], y=percent['p75'],
                         name='75 Percentile of social quality each year',
                         line=dict(color='rgba(0,0,255,0.2)'),
                        showlegend=False,
                        hoverinfo='skip'))
fig.add_trace(go.Scatter(x=percent['year'], y=percent['p25'],
                         name='Interquartile Range of social quality',
                         fill='tonexty',
                        fillcolor='rgba(200,200,200,1)',
                        line=dict(color='rgba(0,0,255,0.2)'),
                        showlegend=True))
fig.update_layout(
    title='Social Quality of Afghanistan vs. the rest of the World',
    xaxis_title='Year',
    yaxis_title='Social Quality'
)
fig.show()

In [522]:
final['is_PAK'] = final['Country Code'] == 'PAK'
is_AFG = final[final['Country Code'] == 'PAK'].sort_values(by='Year')
percent = final[final['Country Code'] != 'PAK'].groupby('Year')[['social quality']]\
    .quantile([0.25, 0.75]).unstack().reset_index().sort_values(by='Year')
percent.columns = ['year', 'p25', 'p75']

fig = go.Figure()
fig.add_trace(go.Scatter(x=is_AFG['Year'], y=is_AFG['social quality'],
                          name='social quality of Pakistan',
                          line=dict(color='red')))
fig.add_trace(go.Scatter(x=percent['year'], y=percent['p75'],
                         name='75 Percentile of social quality each year',
                         line=dict(color='rgba(0,0,255,0.2)'),
                        showlegend=False,
                        hoverinfo='skip'))
fig.add_trace(go.Scatter(x=percent['year'], y=percent['p25'],
                         name='Interquartile Range of social quality',
                         fill='tonexty',
                        fillcolor='rgba(200,200,200,0.7)',
                        line=dict(color='rgba(0,0,255,0.2)'),
                        showlegend=True))
fig.update_layout(
    title='Social Quality of Pakistan vs. The Rest of the World',
    xaxis_title='Year',
    yaxis_title='Social Quality'
)
fig.show()

In [517]:
px.scatter(final[(final['Year']<=2000) & (final['Year']>=1970)], x='social quality', y='Refugee population by country or territory of asylum', color='Country Code')

In [525]:
fig = go.Figure()
fig.add_trace(go.Scatter(
    x=final['social quality'],
    y=final['Refugee population by country or territory of asylum'],
    mode='markers',
    marker=dict(color='lightgray', size=8),
    name='Other countries'
))

# Highlighted group
highlight = final[final['Country Code'] == 'PAK']
fig.add_trace(go.Scatter(
    x=highlight['social quality'],
    y=highlight['Refugee population by country or territory of asylum'],
    mode='markers',
    marker=dict(color='red', size=7, symbol='diamond', line=dict(width=2, color='black')),
    name='Pakistan'
))

fig.update_layout(
    title='Social Quality vs. Refugee Population',
    xaxis_title='Social Quality',
    yaxis_title='Refugee Population'
)

fig.show()

In [504]:
final.groupby('Country Code')[['Refugee population by country or territory of asylum']].mean().sort_values(by='Refugee population by country or territory of asylum', ascending=False)

              Refugee population by country or territory of asylum
Country Code
PAK                                                1.828176e+06
EUU                                                1.616758e+06
IRN                                                1.536688e+06
JOR                                                1.364275e+06
EMU                                                1.353054e+06
...                                                         ...
TUV                                                         NaN
VCT                                                         NaN
VGB                                                         NaN
VIR                                                         NaN
XKX                                                         NaN

[230 rows x 1 columns]

In [527]:
social_dev

,Country Name,Country Code,Year,"Adolescent fertility rate (births per 1,000 women ages 15-19)","Children in employment, female (% of female children ages 7-14)","Children in employment, male (% of male children ages 7-14)","Children in employment, study and work (% of children in employment, ages 7-14)","Children in employment, study and work, female (% of female children in employment, ages 7-14)","Children in employment, study and work, male (% of male children in employment, ages 7-14)","Children in employment, total (% of children ages 7-14)","Children in employment, work only (% of children in employment, ages 7-14)","Children in employment, work only, female (% of female children in employment, ages 7-14)","Children in employment, work only, male (% of male children in employment, ages 7-14)","Labor force participation rate for ages 15-24, female (%) (modeled ILO estimate)","Labor force participation rate for ages 15-24, male (%) (modeled ILO estimate)","Labor force participation rate for ages 15-24, total (%) (modeled ILO estimate)","Labor force participation rate, female (% of female population ages 15+) (modeled ILO estimate)","Labor force participation rate, female (% of female population ages 15-64) (modeled ILO estimate)","Labor force participation rate, male (% of male population ages 15+) (modeled ILO estimate)","Labor force participation rate, male (% of male population ages 15-64) (modeled ILO estimate)","Labor force participation rate, total (% of total population ages 15-64) (modeled ILO estimate)","Life expectancy at birth, female (years)","Life expectancy at birth, male (years)","Literacy rate, youth (ages 15-24), gender parity index (GPI)","Prevalence of HIV, female (% ages 15-24)","Prevalence of HIV, male (% ages 15-24)",Proportion of seats held by women in national parliaments (%),Refugee population by country or territory of asylum,Refugee population by country or territory of origin,"School enrollment, primary (gross), gender parity index (GPI)","School enrollment, primary and secondary (gross), gender parity index (GPI)","School enrollment, secondary (gross), gender parity index (GPI)","School enrollment, tertiary (gross), gender parity index (GPI)","Unemployment, female (% of female labor force) (modeled ILO estimate)","Unemployment, male (% of male labor force) (modeled ILO estimate)","Vulnerable employment, female (% of female employment) (modeled ILO estimate)","Vulnerable employment, male (% of male employment) (modeled ILO estimate)"
0,Afghanistan,AFG,1990,162.835400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.23,64.26,40.11,15.32,15.83,79.16,81.01,49.07,51.442000,49.281000,NaN,0.1,0.1,NaN,50.0,6339095.0,0.54850,NaN,NaN,0.47453,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,1994,164.448600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.30,63.71,40.19,15.36,15.88,78.63,80.56,49.41,54.012000,51.746000,NaN,0.1,0.1,NaN,19134.0,2731166.0,0.50580,0.43200,0.28143,NaN,14.76,11.09,98.600003,90.540001
2,Africa Western and Central,AFW,1969,172.026085,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.162546,39.712956,NaN,NaN,NaN,NaN,131200.0,71050.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Western and Central,AFW,1989,156.266617,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.040823,47.437250,NaN,NaN,NaN,NaN,132129.0,199380.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,1973,224.736000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.449000,40.716000,NaN,NaN,NaN,NaN,NaN,426550.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15405,San Marino,SMR,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.96996,1.08121,1.20937,NaN,NaN,NaN,NaN,NaN
15406,Tanzania,TZA,1961,157.680000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.116000,42.600000,NaN,NaN,NaN,NaN,12000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15407,Tanzania,TZA,1971,155.826200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.375000,45.992000,NaN,NaN,NaN,NaN,71240.0,NaN,0.65777,0.64500,0.41462,0.20924,NaN,NaN,NaN,NaN
15408,Uganda,UGA,1963,173.056000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.647000,44.719000,NaN,NaN,NaN,NaN,59000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15409,Uganda,UGA,2007,150.734000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.50,58.15,55.27,65.46,66.66,76.44,76.91,71.64,55.764000,51.926000,NaN,4.6,1.7,30.722892,228956.0,21325.0,0.99436,0.96106,0.79395,NaN,2.88,2.21,89.010000,74.810000